name: create_or_update_pr
description: "次のステージ用のPRを作成または更新します。"

inputs:
  base_branch:
    description: 'Base branch for the PR'
    required: true
  head_branch:
    description: 'Head branch for the PR'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token for authentication'
    required: true
  pr_number:
    description: 'PR number to update'
    required: false
    default: 'unknown'

runs:
  using: composite
  steps:
    - name: Set up Git
      shell: bash
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Update or Create PR
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        BASE_BRANCH: ${{ inputs.base_branch }}
        HEAD_BRANCH: ${{ inputs.head_branch }}
        PR_TITLE: "自動PR: ${{ inputs.head_branch }} から ${{ inputs.base_branch }} へ更新"
      run: |
        # 最新の HEAD_BRANCH と BASE_BRANCH を取得
        git fetch origin $HEAD_BRANCH $BASE_BRANCH
        
        # 差分があるか確認
        if git diff --quiet origin/$HEAD_BRANCH origin/$BASE_BRANCH; then
          echo "$HEAD_BRANCH と $BASE_BRANCH に差分がありません。アクションは不要です。"
          exit 0
        fi
        
        # HEAD_BRANCHからBASE_BRANCHへのオープンなPRを検索
        EXISTING_PR=$(gh pr list --base $BASE_BRANCH --head $HEAD_BRANCH --state open --json number,title --jq '.[0].number')
        
        if [ -n "$EXISTING_PR" ]; then
          # 既存のPRが見つかった場合、コメントを追加
          echo "既存のPR #$EXISTING_PR が見つかりました。コメントを追加します。"
          
          gh pr comment $EXISTING_PR --body "新しい変更が $HEAD_BRANCH ブランチにマージされました。

        この変更は元PR #${{ inputs.pr_number }} からのものです。

        $HEAD_BRANCH ブランチには新しい変更が含まれています。このPRをマージすると、これらの変更が $BASE_BRANCH に反映されます。"
        else
          # 既存のPRがない場合、新しいPRを作成
          echo "既存のPRが見つかりませんでした。新しいPRを作成します。"

          gh pr create \
            --base $BASE_BRANCH \
            --head $HEAD_BRANCH \
            --title "$PR_TITLE" \
            --body "$HEAD_BRANCH ブランチへのマージに伴い、自動的に $BASE_BRANCH ブランチへの PR を作成しました。

          ## 含まれる変更点
          このPRは最新の $HEAD_BRANCH ブランチの変更を $BASE_BRANCH に反映します。

          マージ元PR: #${{ inputs.pr_number }}"
        fi
