name: Update Staging PR

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  update-staging-pr:
    # プルリクエストがマージされた場合のみ実行
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # すべての履歴を取得（ブランチの比較に必要）

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
      
      - name: Find or create PR to staging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: "自動PR: dev から staging へ更新"
        run: |
          # 最新の dev と staging を取得
          git fetch origin dev staging
          
          # 差分があるか確認
          if git diff --quiet origin/dev origin/staging; then
            echo "dev と staging に差分がありません。アクションは不要です。"
            exit 0
          fi
          
          # devからstagingへのオープンなPRを検索
          EXISTING_PR=$(gh pr list --base staging --head dev --state open --json number,title --jq '.[0].number')
          
          if [ -n "$EXISTING_PR" ]; then
            # 既存のPRが見つかった場合、コメントを追加
            echo "既存のPR #$EXISTING_PR が見つかりました。コメントを追加します。"
            
            gh pr comment $EXISTING_PR --body "新しい変更が dev ブランチにマージされました。

          この変更は元PR #${{ github.event.pull_request.number }} からのものです。

          dev ブランチには新しい変更が含まれています。このPRをマージすると、これらの変更が staging に反映されます。"
          else
            # 既存のPRがない場合、新しいPRを作成
            echo "既存のPRが見つかりませんでした。新しいPRを作成します。"

            gh pr create \
              --base staging \
              --head dev \
              --title "$PR_TITLE" \
              --body "dev ブランチへのマージに伴い、自動的に staging ブランチへの PR を作成しました。

              ## 含まれる変更点
              このPRは最新の dev ブランチの変更を staging に反映します。

              マージ元PR: #${{ github.event.pull_request.number }}"
          fi
